//! Provider-neutral model response.

use crate::{ModelMessage, NormalizedUsage};
use serde::{Deserialize, Serialize};

/// Response returned by a model provider.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelResponse {
    /// Assistant message generated by the provider.
    pub message: ModelMessage,
    /// Normalized token and cost accounting.
    pub usage: NormalizedUsage,
}

impl ModelResponse {
    /// Creates a response from an assistant message and normalized usage.
    pub fn new(message: ModelMessage, usage: NormalizedUsage) -> Self {
        Self { message, usage }
    }
}
